title: "The Engineering Lead, a Dad, a Husband and Myself."
author: "James Ockenden"
description: "Reflections, interactions, and practical lessons from my role in software leadership, family life, and navigating everything in between."
theme: minima
markdown: kramdown
highlighter: rouge
